USE sharktank;
GO

CREATE TABLE dbo.deals (
    id INT IDENTITY(1,1) PRIMARY KEY,
    staging_id INT NULL,
    company NVARCHAR(255),
    season NVARCHAR(50),
    episode_number INT,
    pitch_number INT,
    season_start DATE,
    season_end DATE,
    original_air_date DATE,
    episode_title NVARCHAR(255),
    anchor NVARCHAR(255),
    sector NVARCHAR(255),
    business_description NVARCHAR(MAX),
    company_website NVARCHAR(512),
    started_in NVARCHAR(50),
    founder_count INT,
    male_presenters INT,
    female_presenters INT,
    transgender_presenters INT,
    couple_presenters BIT,
    pitchers_average_age FLOAT,
    pitchers_city NVARCHAR(255),
    pitchers_state NVARCHAR(255),
    yearly_revenue DECIMAL(18,2),
    monthly_sales DECIMAL(18,2),
    gross_margin DECIMAL(5,2),
    net_margin DECIMAL(5,2),
    ebitda DECIMAL(18,2),
    cash_burn DECIMAL(18,2),
    skus INT,
    has_patents BIT,
    bootstrapped BIT,
    part_of_match_off BIT,
    asked_amount DECIMAL(18,2),
    equity_asked DECIMAL(5,2),
    valuation_requested DECIMAL(18,2),
    received_offer NVARCHAR(255),
    accepted_offer NVARCHAR(255),
    invested_amount DECIMAL(18,2),
    equity_final DECIMAL(5,2),
    total_deal_debt DECIMAL(18,2),
    deal_valuation DECIMAL(18,2),
    number_of_sharks_in_deal INT,
    deal_has_conditions BIT,
    royalty_percentage DECIMAL(5,2),
    royalty_recouped_amount DECIMAL(18,2),
    advisory_shares_equity DECIMAL(5,2),
    namita_present BIT,
    vineeta_present BIT,
    anupam_present BIT,
    aman_present BIT,
    peyush_present BIT,
    ritesh_present BIT,
    amit_present BIT,
    guest_present BIT
);
GO
