INSERT INTO dbo.deals (
  staging_id, company, season, episode_number, pitch_number, season_start, season_end,
  original_air_date, episode_title, anchor, sector, business_description, company_website,
  started_in, founder_count, male_presenters, female_presenters, transgender_presenters,
  couple_presenters, pitchers_average_age, pitchers_city, pitchers_state, yearly_revenue,
  monthly_sales, gross_margin, net_margin, ebitda, cash_burn, skus, has_patents, bootstrapped,
  part_of_match_off, asked_amount, equity_asked, valuation_requested, received_offer,
  accepted_offer, invested_amount, equity_final, total_deal_debt, deal_valuation,
  number_of_sharks_in_deal, deal_has_conditions, royalty_percentage, royalty_recouped_amount,
  advisory_shares_equity, namita_present, vineeta_present, anupam_present, aman_present,
  peyush_present, ritesh_present, amit_present, guest_present
)
SELECT
  TRY_CAST(staging_id AS INT),
  TRY_CAST(company AS NVARCHAR(255)),
  TRY_CAST(season AS NVARCHAR(50)),
  TRY_CAST(episode_number AS INT),
  TRY_CAST(pitch_number AS INT),
  TRY_CAST(season_start AS DATE),
  TRY_CAST(season_end AS DATE),
  TRY_CAST(original_air_date AS DATE),
  TRY_CAST(episode_title AS NVARCHAR(255)),
  TRY_CAST(anchor AS NVARCHAR(255)),
  TRY_CAST(sector AS NVARCHAR(255)),
  TRY_CAST(business_description AS NVARCHAR(MAX)),
  TRY_CAST(company_website AS NVARCHAR(512)),
  TRY_CAST(started_in AS NVARCHAR(50)),
  TRY_CAST(founder_count AS INT),
  TRY_CAST(male_presenters AS INT),
  TRY_CAST(female_presenters AS INT),
  TRY_CAST(transgender_presenters AS INT),
  CASE WHEN LOWER(ISNULL(couple_presenters,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  TRY_CAST(pitchers_average_age AS FLOAT),
  TRY_CAST(pitchers_city AS NVARCHAR(255)),
  TRY_CAST(pitchers_state AS NVARCHAR(255)),
  TRY_CONVERT(DECIMAL(18,2), yearly_revenue),
  TRY_CONVERT(DECIMAL(18,2), monthly_sales),
  TRY_CONVERT(DECIMAL(5,2), gross_margin),
  TRY_CONVERT(DECIMAL(5,2), net_margin),
  TRY_CONVERT(DECIMAL(18,2), ebitda),
  TRY_CONVERT(DECIMAL(18,2), cash_burn),
  TRY_CAST(skus AS INT),
  CASE WHEN LOWER(ISNULL(has_patents,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  CASE WHEN LOWER(ISNULL(bootstrapped,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  CASE WHEN LOWER(ISNULL(part_of_match_off,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  TRY_CONVERT(DECIMAL(18,2), asked_amount),
  TRY_CONVERT(DECIMAL(5,2), equity_asked),
  TRY_CONVERT(DECIMAL(18,2), valuation_requested),
  TRY_CAST(received_offer AS NVARCHAR(255)),
  TRY_CAST(accepted_offer AS NVARCHAR(255)),
  TRY_CONVERT(DECIMAL(18,2), invested_amount),
  TRY_CONVERT(DECIMAL(5,2), equity_final),
  TRY_CONVERT(DECIMAL(18,2), total_deal_debt),
  TRY_CONVERT(DECIMAL(18,2), deal_valuation),
  TRY_CAST(number_of_sharks_in_deal AS INT),
  CASE WHEN LOWER(ISNULL(deal_has_conditions,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  TRY_CONVERT(DECIMAL(5,2), royalty_percentage),
  TRY_CONVERT(DECIMAL(18,2), royalty_recouped_amount),
  TRY_CONVERT(DECIMAL(5,2), advisory_shares_equity),
  CASE WHEN LOWER(ISNULL(namita_present,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  CASE WHEN LOWER(ISNULL(vineeta_present,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  CASE WHEN LOWER(ISNULL(anupam_present,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  CASE WHEN LOWER(ISNULL(aman_present,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  CASE WHEN LOWER(ISNULL(peyush_present,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  CASE WHEN LOWER(ISNULL(ritesh_present,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  CASE WHEN LOWER(ISNULL(amit_present,'')) IN ('1','true','yes') THEN 1 ELSE 0 END,
  CASE WHEN LOWER(ISNULL(guest_present,'')) IN ('1','true','yes') THEN 1 ELSE 0 END
FROM dbo.staging_deals_clean;
